# Generated by Django 5.0.1 on 2024-01-24 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Books',
            new_name='Todo',
        ),
    ]
